apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: kube-system
  labels:
    k8s-app: coredns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "CoreDNS"
spec:
  selector:
    k8s-app: coredns
  clusterIP: 10.254.0.20
  ports:
  - name: dns
    port: 53
    protocol: UDP
  #- name: dns-tcp
  #  port: 53
  #  protocol: TCP
