apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: k8s
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
    nodePort: 30911
  selector:
    app: grafana
  type: NodePort
