version: '2'

networks:
  monitoring_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.22.0/24
          gateway: 172.16.22.1

services:
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - /home/controller/Desktop/controller-repo/monitor-test/monitoring_docker/prometheus/etc:/etc/prometheus/
      - /home/controller/Desktop/controller-repo/monitor-test/monitoring_docker/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      monitoring_bridge:
        ipv4_address: 172.16.22.2
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3007:3000
    volumes:
      - /home/controller/Desktop/controller-repo/monitor-test/monitoring_docker/grafana/data:/var/lib/grafana
      - /home/controller/Desktop/controller-repo/monitor-test/monitoring_docker/grafana/etc/provisioning/:/etc/grafana/provisioning/
    #env_file:
    #  - ./grafana/config.monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      monitoring_bridge:
        ipv4_address: 172.16.22.3
    restart: always
