apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: httpd
  annotations:
    prometheus.io/scrape: 'true'
  name: httpd
  namespace: k8s
spec:
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: httpd
  sessionAffinity: None
  type: ClusterIP
