apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: kube-system
  labels:
    name: nginx-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-demo
  template:
    metadata:
      labels:
        name: nginx-demo
    spec:
      containers:
      - name: nginx-demo
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
  namespace: kube-system
  labels:
    name: nginx-demo-nodeport-svc
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30180
      name: http
    - port: 443
      nodePort: 31443
      name: https
  selector:
    name: nginx-demo
