apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: kube-system  
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      hostNetwork: true 
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80

