apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registrator
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registrator
        member: registrator
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: registrator
          image: "gliderlabs/registrator:master"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            
          command: ["/bin/sh"]
          args: ["-c", "registrator -internal consul://$(CONSUL_1_SERVICE_HOST):8500"]  
          volumeMounts:
            - name: docker-sock
              mountPath: /tmp/docker.sock
            
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - echo \"nameserver  $(CONSUL_1_SERVICE_HOST)\" > /etc/resolv.conf

      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
